### ISSUE TITLE
OwO bot is stuck!

### ISSUE THREAD

**Issue by Ziemniakoss** [kowalskiPl/OwO_bot#10] opened 2023-01-03 18:55 UTC
I was playing my favorite barbie music and someone called me so I pressed "stop" on bot control panel.
When I came back I noticed something truly  horrible: OwO bot was stuck!
I tried to help him but control panel was gone!

## Steps to reproduce (bug, not with bot)

- `!play barbie`
- select favorite barbie music
- press stop on control panel

**Comment by kowalskiPl** [comment] 2023-01-03 19:11
This was intended behavior however it's marked to be changed as it's confusing. Once the major refactor of all bot systems is done, this will be taken care of

**Comment by kowalskiPl** [comment] 2023-01-05 15:13
Closed in https://github.com/kowalskiPl/OwO_bot/pull/12

**Closed by kowalskiPl** 2023-01-05 15:13 UTC
